### ISSUE TITLE
Melos doesn't resolve packages or dependency graph

### ISSUE THREAD

**Issue by lukepighetti** [blaugold/melos-code#30]
When I open [this project](https://github.com/lukepighetti/spike_melos_task/tree/6a9aa4f9c1e2bde0c7ff757ed05315644b1bc774) and type `melos list` it only lists the `styles` package even though there is a `widgets` package that is consumed by the root app which depends on `styles`

```
% melos list --graph
{
  "styles": []
}
```

**Comment by blaugold** [comment]
The `widgets` package pubspec includes `publish_to: "none"`. These packages are private in Melos, in the sense that they won't be versioned or published. `melos list` does not include those packages by default but does so with the `--all` flag.

```
➜  spike_melos_task git:(master) ✗ melos list --all --graph
{
  "styles": [],
  "widgets": [
    "styles"
  ]
}
```

Side note: This issue probably belongs in the [melos](https://github.com/invertase/melos) repo :)

**Comment by lukepighetti** [comment]
Thank you for providing a clear answer and my apologies for posting it in the wrong repo.

**Comment by blaugold** [comment]
No problem. Glad I could help.
