### ISSUE TITLE
Support Melos 3.0.0

### ISSUE THREAD

**Issue by MELICI0US** [blaugold/melos-code#44]
Melos has just released a new version with some breaking changes. This extension is not currently compatible with it

**Comment by EugeneLes** [comment]
Are there any updates on this?

**Comment by blaugold** [comment]
@EugeneLes Sorry for not responding earlier. I'll hopefully have some time this weekend to get to updating the extension.

**Comment by fstof** [comment]
I think the melos.yaml schema is still not up to date...

In my case having post clean hooks vscode complains about "clean" property not being allowed

**Comment by blaugold** [comment]
@fstof Thanks for letting me know! I've just published a new version with an updated schema.
