### ISSUE TITLE
Support dependencies and dev_dependencies within melos.yaml

### ISSUE THREAD

**Issue by DFelten** [blaugold/melos-code#52]
With [version 3.2.0](https://pub.dev/packages/melos/changelog#320) of melos common dependencies are possible. Now dependencies and dev_dependencies are possible within the melos.yaml. Currently they are recognized as an error:

![CleanShot 2023-10-25 at 08 23 11@2x](https://github.com/blaugold/melos-code/assets/1169185/e344fcc2-5055-40f5-95ce-5c09e2389852)

**Comment by DFelten** [comment]
@blaugold Thanks for the update! Unfortunately `dev_dependencies` is still not working with version 1.1.0 of the extension

![CleanShot 2024-01-02 at 21 44 52@2x](https://github.com/blaugold/melos-code/assets/1169185/f5ca511d-8618-4a20-91b7-20ccd31edafd)

**Comment by blaugold** [comment]
Ah, yes. 😬 Thanks for letting me know! Most of the configuration in keys in `melos.yaml` use camel-case, but `dev_dependencies` does not. Version `1.1.1` of the extension has a fix.

**Comment by DFelten** [comment]
Thanks, now it's working!
