### ISSUE TITLE
Disable `dart.runPubGetOnPubspecChanges` automatically

### ISSUE THREAD

**Issue by Salakar** [blaugold/melos-code#8]
Not sure if possible with this extension but if we could have this disabled automatically that'd be cool - https://github.com/FirebaseExtended/flutterfire/blob/master/.vscode/settings.json#L2

Why; pub get will break melos generated files since it installs as no longer interlinking packages.

**Comment by blaugold** [comment]
I think we can do that.

**Comment by bartekpacia** [comment]
Is there some switch to disable this behavior? It's annoying. @Salakar @blaugold

**Comment by blaugold** [comment]
@bartekpacia There currently is not. I've created an issue to disable this feature for Melos workspaces that `usePubspecOverrides` (https://github.com/blaugold/melos-code/issues/36).

**Comment by bartekpacia** [comment]
Thanks for the blazing fast response! 💙
